version: '3.8'

services:
  web:
    build: ./project
    command: uvicorn project.app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/tech1_user_service
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15.3
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo