"""add relationship

Revision ID: 849f9f7583b2
Revises: 579371e65cde
Create Date: 2023-09-23 17:46:19.011710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849f9f7583b2'
down_revision = '579371e65cde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###